Add explaining-signet to bitcoin-magazine/bitcoin-explained
bitcointranscripts/bitcointranscripts pull request #299
Opened 2023-11-17 05:45 UTC by spraveenitpro

This PR adds [Explaining Signet](https://www.youtube.com/watch?v=lGJaIbpf6bk) transcript to the bitcoin-magazine/bitcoin-explained directory.

2023-11-18 19:04 UTC, adamjonas requested changes
@spraveenitpro There are a number for updates, especially people's names, needed before this is ready for merge.

2023-11-18 19:04 UTC, adamjonas commented on bitcoin-magazine/bitcoin-explained/explaining-signet.md
> +Speaker 0: 00:00:07
These speaker names need to be replaced throughout

2023-11-18 19:04 UTC, adamjonas commented on bitcoin-magazine/bitcoin-explained/explaining-signet.md
> +Live from Utrecht, this is the fan weirdum Sjoerds Nedo. Hello! Sjoerds, welcome.
The show name and speakers names need updates

2023-11-18 19:04 UTC, adamjonas commented on bitcoin-magazine/bitcoin-explained/explaining-signet.md
> +Yeah, it's basically a clone of mainnet which was created I think by, I think Gavin and Driesen created this back in, what would have been 2011, 12, 13? Probably before, I don't know.
Gavin's name needs updating

2023-11-25 00:56 UTC, kouloumos commented
@spraveenitpro, Since we haven't got any response from you, I'll go ahead and close this submission. This will provide others with the chance to review it or for you to to revisit it.

We hope to see your work in the future. Thank you!

2023-11-25 00:56 UTC, closed without merging